# -*- coding: utf-8 -*-
"""DS_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YGWuea5g4RmMfq4ieDXTUaVp-LtUbkPf
"""

from google.colab import drive
drive.mount('/content/drive')

!ls '/content/drive/MyDrive/colab'

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel("/content/drive/MyDrive/colab/DS - Assignment Part 1 data set.xlsx")

df

sns.distplot(df['House Age'],hist = False,color = 'red')
sns.distplot(df['House price of unit area'],hist = False, color = 'green')

sns.distplot(df['Distance from nearest Metro station (km)'],hist = False,color = 'red')
sns.distplot(df['House price of unit area'],hist = False, color = 'green')

sns.distplot(df['Number of convenience stores'],hist = False,color = 'red')
sns.distplot(df['House price of unit area'],hist = False, color = 'green')

sns.distplot(df['Number of bedrooms'],hist = False,color = 'red')
sns.distplot(df['House price of unit area'],hist = False, color = 'green')

sns.distplot(df['House price of unit area'], kde = False)

